[build]
  functions = "functions"
  publish = "public"
  command = "npm run build"

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  external_node_modules = ["express", "mongoose"]
  included_files = ["Route/**/*", "controller/**/*", "model/**/*"]

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/users/*"
  to = "/.netlify/functions/api/users/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
