[build]
  functions = "functions"
  command = "npm run build"

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  included_files = ["./Route/**/*", "./controller/**/*", "./model/**/*"]

[[redirects]]
  from = "/"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/users/*"
  to = "/.netlify/functions/api/users/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
